- hosts: save
  become: yes
  tasks:
    - name: Create backup folder
      file:
        path: /backup/images
        state: directory
        owner: root
        recurse: yes

    - name: Save Jenkins image in .tar
      shell: docker save -o jenkins.tar jenkins
      args: 
        chdir: /backup/images

    - name: Save Grafana image in .tar
      shell: docker save -o grafana.tar grafana/grafana:8.4.4
      args: 
        chdir: /backup/images

    - name: Save Prometheus image in .tar
      shell: docker save -o prometheus.tar prom/prometheus:v2.34.0
      args: 
        chdir: /backup/images
    
    - name: Save Node Exporter image in .tar
      shell: docker save -o node_exporter.tar quay.io/prometheus/node-exporter:latest
      args: 
        chdir: /backup/images